spring.application.name=library

spring.datasource.hikari.jdbc-url=jdbc:postgresql://localhost:5432/spring_library_api
spring.datasource.hikari.username=spring_library_api_user
spring.datasource.hikari.password=password
spring.datasource.hikari.driver-class-name=org.postgresql.Driver

spring.sql.init.schema-locations=classpath:/sql/schema.psql
spring.sql.init.mode=always

spring.jackson.deserialization.fail-on-unknown-properties=true